const FAKE_CONST = {
  poplularFood: [
    {
      id: 1,
      image: require("../assets/media/popular/pop1.jpg"),
      title: "پیتزا",
    },
    {
      id: 2,
      image: require("../assets/media/popular/pop2.jpg"),
      title: "کباب",
    },
    {
      id: 3,
      image: require("../assets/media/popular/pop3.jpg"),
      title: "سوپ",
    },
    {
      id: 4,
      image: require("../assets/media/popular/pop4.jpg"),
      title: "ساندویچ",
    },
    {
      id: 5,
      image: require("../assets/media/popular/pop5.jpg"),
      title: "غذای ایرانی",
    },
    {
      id: 6,
      image: require("../assets/media/popular/pop6.jpg"),
      title: "سوخاری",
    },
    {
      id: 7,
      image: require("../assets/media/popular/pop7.jpg"),
      title: "پاستا",
    },
    {
      id: 8,
      image: require("../assets/media/popular/pop8.jpg"),
      title: "سالاد",
    },
    {
      id: 9,
      image: require("../assets/media/popular/pop9.jpg"),
      title: "صبحانه",
    },
    {
      id: 10,
      image: require("../assets/media/popular/pop10.jpg"),
      title: "استیک",
    },
  ],
  appLinks: [
    { id: 1, img: require("../assets/media/Main-screen/img19.png") },
    { id: 2, img: require("../assets/media/Main-screen/img18.png") },
    { id: 3, img: require("../assets/media/Main-screen/img21.png") },
    { id: 4, img: require("../assets/media/Main-screen/img20.png") },
  ],
  tizerImg: [
    { id: 1, img: require("../assets/media/Main-screen/img1.jpg") },
    { id: 2, img: require("../assets/media/Main-screen/img2.jpg") },
    { id: 3, img: require("../assets/media/Main-screen/img3.jpg") },
  ],
  cartList: [
    {
      id: 1,
      mainImg: require("../assets/media/Main-screen/img15.jpg"),
      logoImg: require("../assets/media/logo/img16.png"),
      discount: "null",
      titlerest: "رستوران بوکا",
      addressParant: "(دروس)",
      address: "دروس",
      people: "(24نفر)",
      time: "24 - 45",
    },
    {
      id: 2,
      mainImg: require("../assets/media/Main-screen/img26.jpg"),
      logoImg: require("../assets/media/logo/img22.jpg"),
      discount: "10",
      titlerest: "رستوران بین المللی تاویت",
      addressParant: "null",
      address: "ونک",
      people: "(24نفر)",
      time: "24 - 45",
    },
    {
      id: 3,
      mainImg: require("../assets/media/Main-screen/img27.jpg"),
      logoImg: require("../assets/media/logo/img23.png"),
      discount: "20",
      titlerest: "رستوران ژاپنی کاتسو",
      addressParant: "null",
      address: "زعفرانیه",
      people: "(124نفر)",
      time: "24 - 45",
    },
    {
      id: 4,
      mainImg: require("../assets/media/Main-screen/img29.jpg"),
      logoImg: require("../assets/media/logo/img24.png"),
      discount: "20",
      titlerest: " پیتزا آهو",
      addressParant: "null",
      address: "یوسف آباد",
      people: "(4نفر)",
      time: "24 - 45",
    },
    {
      id: 5,
      mainImg: require("../assets/media/Main-screen/img15.jpg"),
      logoImg: require("../assets/media/logo/img16.png"),
      discount: "10",
      titlerest: "رستوران بوکا",
      addressParant: "(دروس)",
      address: "دروس",
      people: "(24نفر)",
      time: "24 - 45",
    },
  ],
  cartListNewest: [
    {
      id: 1,
      mainImg: require("../assets/media/Main-screen/img15.jpg"),
      logoImg: require("../assets/media/logo/img16.png"),
      discount: "null",
      titlerest: "رستوران بوکا",
      addressParant: "(دروس)",
      address: "دروس",
      people: "(24نفر)",
      time: "24 - 45",
    },
  ],
  logo: [
    {
      id: 1,
      logo: require("../assets/media/logo/img39.png"),
    },
    {
      id: 2,
      logo: require("../assets/media/logo/img38.png"),
    },
    {
      id: 3,
      logo: require("../assets/media/logo/img37.png"),
    },
    {
      id: 4,
      logo: require("../assets/media/logo/img35.png"),
    },
    {
      id: 5,
      logo: require("../assets/media/logo/img34.png"),
    },
    {
      id: 6,
      logo: require("../assets/media/logo/img33.png"),
    },
    {
      id: 7,
      logo: require("../assets/media/logo/img31.png"),
    },
    {
      id: 8,
      logo: require("../assets/media/logo/img45.png"),
    },
    {
      id: 9,
      logo: require("../assets/media/logo/img44.png"),
    },
    {
      id: 10,
      logo: require("../assets/media/logo/img43.png"),
    },
    {
      id: 11,
      logo: require("../assets/media/logo/img42.png"),
    },
    {
      id: 12,
      logo: require("../assets/media/logo/img41.png"),
    },
    {
      id: 13,
      logo: require("../assets/media/logo/img40.png"),
    },
    {
      id: 14,
      logo: require("../assets/media/logo/img16.png"),
    },
    {
      id: 15,
      logo: require("../assets/media/logo/img55.png"),
    },
    {
      id: 16,
      logo: require("../assets/media/logo/img53.png"),
    },
    {
      id: 17,
      logo: require("../assets/media/logo/img52.png"),
    },
    {
      id: 18,
      logo: require("../assets/media/logo/img51.png"),
    },
    {
      id: 19,
      logo: require("../assets/media/logo/img49.png"),
    },
    {
      id: 20,
      logo: require("../assets/media/logo/img48.png"),
    },
    {
      id: 21,
      logo: require("../assets/media/logo/img47.png"),
    },
  ],
  cartFoodList: [
    {
      menuImg: require("../assets/media/Rest-screen/rice3.png"),
      category: "1پیتزا",
      key: "1",
      detail: [
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "مارگینا پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "10",
        },
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "پپرون پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "20",
        },
      ],
    },
    {
      menuImg: require("../assets/media/Rest-screen/bowl.png"),
      category: "2پیتزا",
      key: "2",
      detail: [
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "مارگینا پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "10",
        },
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "پپرون پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "20",
        },
      ],
    },
    {
      menuImg: require("../assets/media/Rest-screen/rice3.png"),
      category: "3پیتزا",
      key: "3",
      detail: [
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "مارگینا پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "10",
        },
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "پپرون پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "20",
        },
      ],
    },
    {
      menuImg: require("../assets/media/Rest-screen/bowl.png"),
      category: "4پیتزا",
      key: "4",
      detail: [
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "مارگینا پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "10",
        },
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "پپرون پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "20",
        },
      ],
    },
    {
      menuImg: require("../assets/media/Rest-screen/rice3.png"),
      category: "5پیتزا",
      key: "5",
      detail: [
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "مارگینا پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "10",
        },
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "پپرون پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "20",
        },
      ],
    },
    {
      menuImg: require("../assets/media/Rest-screen/bowl.png"),
      category: "غذای اصلی",
      key: "6",
      detail: [
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "غذای اصلی پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "10",
        },
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "پپرون عذای اصلی",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "20",
        },
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "غذای اصلی پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "10",
        },
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "پپرون عذای اصلی",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "20",
        },
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "غذای اصلی پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "10",
        },
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "پپرون عذای اصلی",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "20",
        },
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "غذای اصلی پیتزا",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "10",
        },
        {
          img: require("../assets/media/popular/pop1.jpg"),
          title: "پپرون عذای اصلی",
          desc: "سس پیتزا، ریحان، پنیر موزاریلا",
          price: "قیمت از 3500 تومان",
          discount: "20",
        },
      ],
    },
  ],
  cartListSearch: [
    {
      mainImg: require("../assets/media/Main-screen/img15.jpg"),
      logoImg: require("../assets/media/logo/img16.png"),
      discount: "null",
      titlerest: "رستوران بوکا",
      addressParant: "(دروس)",
      address: "دروس",
      people: "(24نفر)",
      time: "24 - 45",
    },
    {
      mainImg: require("../assets/media/Main-screen/img26.jpg"),
      logoImg: require("../assets/media/logo/img22.jpg"),
      discount: "10",
      titlerest: "رستوران بین المللی تاویت",
      addressParant: "null",
      address: "ونک",
      people: "(24نفر)",
      time: "24 - 45",
    },
    {
      mainImg: require("../assets/media/Main-screen/img26.jpg"),
      logoImg: require("../assets/media/logo/img22.jpg"),
      discount: "10",
      titlerest: "رستوران بین المللی تاویت",
      addressParant: "null",
      address: "ونک",
      people: "(24نفر)",
      time: "24 - 45",
    },
    {
      mainImg: require("../assets/media/Main-screen/img26.jpg"),
      logoImg: require("../assets/media/logo/img22.jpg"),
      discount: "10",
      titlerest: "رستوران بین المللی تاویت",
      addressParant: "null",
      address: "ونک",
      people: "(24نفر)",
      time: "24 - 45",
    },
  ],
  cartListRelatedSearch: [
    {
      mainImg: require("../assets/media/Main-screen/img15.jpg"),
      logoImg: require("../assets/media/logo/img16.png"),
      discount: "null",
      titlerest: "رستوران بوکا",
      addressParant: "(دروس)",
      address: "دروس",
      people: "(24نفر)",
      time: "24 - 45",
    },
    {
      mainImg: require("../assets/media/Main-screen/img26.jpg"),
      logoImg: require("../assets/media/logo/img22.jpg"),
      discount: "10",
      titlerest: "رستوران بین المللی تاویت",
      addressParant: "null",
      address: "ونک",
      people: "(24نفر)",
      time: "24 - 45",
    },
    // {
    //   mainImg: require("../assets/media/Main-screen/img26.jpg"),
    //   logoImg: require("../assets/media/logo/img22.jpg"),
    //   discount: "10",
    //   titlerest: "رستوران بین المللی تاویت",
    //   addressParant: "null",
    //   address: "ونک",
    //   people: "(24نفر)",
    //   time: "24 - 45",
    // },
    // {
    //   mainImg: require("../assets/media/Main-screen/img26.jpg"),
    //   logoImg: require("../assets/media/logo/img22.jpg"),
    //   discount: "10",
    //   titlerest: "رستوران بین المللی تاویت",
    //   addressParant: "null",
    //   address: "ونک",
    //   people: "(24نفر)",
    //   time: "24 - 45",
    // },
  ],
};
export default FAKE_CONST;
